siso: grpc keepalive time to 30s
20s may cause
 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_ping"

use 30s

Bug: b/290693904
Change-Id: I42042ab5ec0be76e6f202653d8bff9630d1341d4
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4680687
Reviewed-by: Philipp Wollermann <philwo@google.com>
Commit-Queue: Philipp Wollermann <philwo@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#58135}
GitOrigin-RevId: 3d7023bc8e128c8a74a541ce494f1fe6bc615046