Revert "siso: remove stale local output"
This reverts commit 6fab52db13f63c979bf814bbe130c85993e0ba6b.

Reason for revert:
https://ci.chromium.org/ui/p/chrome/builders/try/linux-chromium-dbg-cog-cache-warmer/30252/overview
```
[19495/22979] ACTION //tools/v8_context_snapshot:generate_v8_context_snapshot(//build/toolchain/linux:clang_x64)
python3 ../../build/gn_run_binary.py ./v8_context_snapshot_generator --snapshot_blob=snapshot_blob.bin --output_file=v8_context_snapshot.bin
././v8_context_snapshot_generator: error while loading shared libraries: libperformance_manager_public_mojom_blink.so: cannot open shared object file: No such file or directory
./v8_context_snapshot_generator failed with exit code 127
exit=127
error: 1 steps failed: exit=127
```

Original change's description:
> siso: remove stale local output
>
> When output_local_strategy=minimum,
> - step A produces A.out
> - step B depends on step A, but not list A.out as input
> - old A.out exists on disk
>
> In this case, step B accidentally access old A.out,
> even if step A produces new A.out in hashfs,
> and might produce different output by step B.
>
> To make it more deterministic, remove such stale output
> on the disk, if output would not be flushed to the disk.
>
> Change-Id: I6803693c748d5707e4d64f3d4c4edc2a460aea4b
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/6345974
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Cr-Commit-Position: refs/heads/main@{#72191}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ic29283120f186af6e7f6674484016cce1ea74476
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/6347436
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#72192}
GitOrigin-RevId: ba0eaa620a25b98a0c4056140bce31562af0dff2